# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UIv1.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 740)
        Form.setMinimumSize(QtCore.QSize(1280, 740))
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vboxlayout = QtWidgets.QVBoxLayout(Form)
        self.vboxlayout.setContentsMargins(-1, 8, -1, -1)
        self.vboxlayout.setObjectName("vboxlayout")
        self.info_layout = QtWidgets.QVBoxLayout()
        self.info_layout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.info_layout.setContentsMargins(5, 5, 5, -1)
        self.info_layout.setObjectName("info_layout")
        self.Title_label = QtWidgets.QLabel(Form)
        self.Title_label.setObjectName("Title_label")
        self.info_layout.addWidget(self.Title_label, 0, QtCore.Qt.AlignHCenter)
        self.info_grid = QtWidgets.QGridLayout()
        self.info_grid.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.info_grid.setObjectName("info_grid")
        self.line_num = QtWidgets.QLabel(Form)
        self.line_num.setMinimumSize(QtCore.QSize(240, 48))
        self.line_num.setObjectName("line_num")
        self.info_grid.addWidget(self.line_num, 1, 1, 1, 1)
        self.mode_select_box = QtWidgets.QGroupBox(Form)
        self.mode_select_box.setMinimumSize(QtCore.QSize(480, 0))
        self.mode_select_box.setMaximumSize(QtCore.QSize(480, 16777215))
        self.mode_select_box.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mode_select_box.setAutoFillBackground(False)
        self.mode_select_box.setObjectName("mode_select_box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mode_select_box)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Both_rB = QtWidgets.QRadioButton(self.mode_select_box)
        self.Both_rB.setChecked(True)
        self.Both_rB.setObjectName("Both_rB")
        self.horizontalLayout.addWidget(self.Both_rB)
        self.L0_rB = QtWidgets.QRadioButton(self.mode_select_box)
        self.L0_rB.setObjectName("L0_rB")
        self.horizontalLayout.addWidget(self.L0_rB)
        self.L1_rB = QtWidgets.QRadioButton(self.mode_select_box)
        self.L1_rB.setObjectName("L1_rB")
        self.horizontalLayout.addWidget(self.L1_rB)
        self.info_grid.addWidget(self.mode_select_box, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.Area_label = QtWidgets.QLabel(Form)
        self.Area_label.setMinimumSize(QtCore.QSize(240, 48))
        self.Area_label.setObjectName("Area_label")
        self.info_grid.addWidget(self.Area_label, 0, 1, 1, 1)
        self.line_class = QtWidgets.QLabel(Form)
        self.line_class.setMinimumSize(QtCore.QSize(240, 48))
        self.line_class.setObjectName("line_class")
        self.info_grid.addWidget(self.line_class, 1, 0, 1, 1)
        self.time_label = QtWidgets.QLabel(Form)
        self.time_label.setMinimumSize(QtCore.QSize(240, 48))
        self.time_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_label.setScaledContents(True)
        self.time_label.setObjectName("time_label")
        self.info_grid.addWidget(self.time_label, 0, 0, 1, 1)
        self.info_comm_grid = QtWidgets.QGridLayout()
        self.info_comm_grid.setObjectName("info_comm_grid")
        self.comm_label = QtWidgets.QLabel(Form)
        self.comm_label.setObjectName("comm_label")
        self.info_comm_grid.addWidget(self.comm_label, 1, 0, 1, 1)
        self.comm_lineedit = QtWidgets.QLineEdit(Form)
        self.comm_lineedit.setObjectName("comm_lineedit")
        self.info_comm_grid.addWidget(self.comm_lineedit, 1, 1, 1, 1)
        self.info_grid.addLayout(self.info_comm_grid, 1, 2, 1, 1)
        self.info_layout.addLayout(self.info_grid)
        self.vboxlayout.addLayout(self.info_layout)
        self.cam_layout = QtWidgets.QHBoxLayout()
        self.cam_layout.setObjectName("cam_layout")
        self.left_cam_view = QtWidgets.QGraphicsView(Form)
        self.left_cam_view.setMinimumSize(QtCore.QSize(320, 320))
        self.left_cam_view.setObjectName("left_cam_view")
        self.cam_layout.addWidget(self.left_cam_view)
        self.right_cam_view = QtWidgets.QGraphicsView(Form)
        self.right_cam_view.setMinimumSize(QtCore.QSize(320, 320))
        self.right_cam_view.setObjectName("right_cam_view")
        self.cam_layout.addWidget(self.right_cam_view)
        self.confirm_view = QtWidgets.QGraphicsView(Form)
        self.confirm_view.setMinimumSize(QtCore.QSize(320, 320))
        self.confirm_view.setObjectName("confirm_view")
        self.cam_layout.addWidget(self.confirm_view)
        self.vboxlayout.addLayout(self.cam_layout)
        self.obj_table = QtWidgets.QTableWidget(Form)
        self.obj_table.setMinimumSize(QtCore.QSize(960, 240))
        self.obj_table.setObjectName("obj_table")
        self.obj_table.setColumnCount(0)
        self.obj_table.setRowCount(0)
        self.vboxlayout.addWidget(self.obj_table)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TRA_railway_object_detection_pre_alpha_v0.1"))
        self.Title_label.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:16pt; text-decoration: underline;\">軌道扣件缺失即時辨識系統</span></p></body></html>"))
        self.line_num.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">軌別:O軌</span></p></body></html>"))
        self.mode_select_box.setTitle(_translate("Form", "結果顯示模式"))
        self.Both_rB.setText(_translate("Form", "顯示所有項目"))
        self.L0_rB.setText(_translate("Form", "僅顯示L0"))
        self.L1_rB.setText(_translate("Form", "僅顯示L1"))
        self.Area_label.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">區間:XX線</span></p></body></html>"))
        self.line_class.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">線別:X線</span></p></body></html>"))
        self.time_label.setText(_translate("Form", "<html><head/><body><p align=\"justify\"><span style=\" font-size:12pt;\">日期:0000/00/00</span></p></body></html>"))
        self.comm_label.setText(_translate("Form", "備註:"))
